// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Ul0wavbEyxJvbszXuIn2TqwWgc55B_M',
    appId: '1:754019585008:web:b1b4efeb6662c485cd6b35',
    messagingSenderId: '754019585008',
    projectId: 'quizbuzz-da502',
    authDomain: 'quizbuzz-da502.firebaseapp.com',
    databaseURL: 'https://quizbuzz-da502-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quizbuzz-da502.firebasestorage.app',
    measurementId: 'G-TLST1VFYET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbg774VtaPu-RN9m1DB5DInAnGsvv1Ksk',
    appId: '1:754019585008:android:3a687f7d5ec32682cd6b35',
    messagingSenderId: '754019585008',
    projectId: 'quizbuzz-da502',
    databaseURL: 'https://quizbuzz-da502-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quizbuzz-da502.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG-f8GdUaSpNvM0YRBGxkK6YHNfmiHT3k',
    appId: '1:754019585008:ios:4b3ad7c893f1e529cd6b35',
    messagingSenderId: '754019585008',
    projectId: 'quizbuzz-da502',
    databaseURL: 'https://quizbuzz-da502-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quizbuzz-da502.firebasestorage.app',
    iosBundleId: 'com.example.quizbuz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG-f8GdUaSpNvM0YRBGxkK6YHNfmiHT3k',
    appId: '1:754019585008:ios:4b3ad7c893f1e529cd6b35',
    messagingSenderId: '754019585008',
    projectId: 'quizbuzz-da502',
    databaseURL: 'https://quizbuzz-da502-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quizbuzz-da502.firebasestorage.app',
    iosBundleId: 'com.example.quizbuz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4Ul0wavbEyxJvbszXuIn2TqwWgc55B_M',
    appId: '1:754019585008:web:9243409873f1e715cd6b35',
    messagingSenderId: '754019585008',
    projectId: 'quizbuzz-da502',
    authDomain: 'quizbuzz-da502.firebaseapp.com',
    databaseURL: 'https://quizbuzz-da502-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quizbuzz-da502.firebasestorage.app',
    measurementId: 'G-8GS9HF4PL1',
  );
}
